#!/bin/bash
# -h,--host 参数主机IP地址
# -p,--port 参数为端口号
# -e --cmd  参数为command
# 长选项 可以使用 "=" 或者空格做连接符
eval set -- $(getopt --options h:p:c: --longoptions host:,port:,cmd: --name 'shcmd.sh' -- "$@")
function usage() {
echo $"Usage:./shcmd -h IP -p PORT --cmd YOUR_CMD"
}
while [ $# -gt 0 ] 
do
        case "$1" in 
        -h|--host)
                host=$2
                shift 2
                ;;
        -p|--port)
                port=$2
                shift 2
                ;;
        -c|--cmd)
                cmd=$2
                shift 2
                ;;
        *)
                usage
                exit
                ;;
esac
[[ x$host != x && x$port != x && x$cmd != x ]]\
&& ssh -p $port root@$host "$cmd" \
&& [ $? != 0 ] && echo -e "Failed~\nCheck err_log for more details."
done
