#!/bin/bash
#Tomcat startup script 
[ "$UID" -ne 0 ] && echo "Permission denied,you need to be root." &&  exit \
|| echo "Ready to perform..."

SCRIPT_PID=$$
TOMCAT_HOME=/usr/local/tomcat7
TOMCAT_START=$TOMCAT_HOME/bin/startup.sh
SCHOOL_SERVER_PATH=school
export SCHOOL_SERVER_PATH
JAVA_HOME=/usr/local/java/jdk1.7.0_65
export JRE_HOME=/usr/local/java/jdk1.7.0_65/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH

. /lib/lsb/init-functions

#Check for tomcat script
if [ ! -f $TOMCAT_HOME/bin/catalina.sh ]
then
    echo Tomcat not available
    exit
fi
start() {
    echo -n Starting Tomcat
    $TOMCAT_START
    RETVAL=$?
    echo
    sleep 1
    [ $RETVAL -eq 0 ] && echo "Tomcat Started !"
#Instead should check to see if apache is up by looking for httpd.pid
}
stop() {
    echo -n $"Shutting down Tomcat..."
    ID=$(ps -ef | grep 'java' | egrep -v "grep|$SCRIPT_PID" | awk '{print $2 }')
    for id in $ID
        do
        echo "Java Pid is $id"
        kill -9 $id
        done
    echo "Tomcat stopped."
}
update() {
cd /usr/local/tomcat7/webapps/ROOT && git pull
[ $? -eq 0 ] && echo "Already up-to-date"
}
update_restart() {
        cd /usr/local/tomcat7/webapps/ROOT && /usr/bin/git pull
         [ $? -eq 0 ] && echo "### Sucessfully up-to-date ###"
}
case "$1" in
        start)
             start
                ;;
        stop)
             stop
                ;;
        restart)
             stop && sleep 1
             start
                ;;
        update)
              update
                ;;
        update_restart)
             update_restart && stop && sleep 1 && start
                ;;
           *)
             echo $"Usage:$0 {start|stop|restart|update|update_restart}"
                ;;
esac
